// Mock data for development

import { Category, Ad } from "@/types";

export const mockCategories: Category[] = [
  {
    id: "cars",
    name: "سيارات",
    slug: "cars",
    image: "/assets/images/categories/cars.jpg",
    icon: "�",
    description: "جميع أنواع السيارات والمركبات",
    subcategories: [
      {
        id: "sedan",
        name: "سيدان",
        slug: "sedan",
        categoryId: "cars",
        count: 150,
      },
      {
        id: "suv",
        name: "دفع رباعي",
        slug: "suv",
        categoryId: "cars",
        count: 89,
      },
      {
        id: "hatchback",
        name: "هاتشباك",
        slug: "hatchback",
        categoryId: "cars",
        count: 45,
      },
      {
        id: "pickup",
        name: "بك أب",
        slug: "pickup",
        categoryId: "cars",
        count: 67,
      },
      {
        id: "luxury",
        name: "سيارات فاخرة",
        slug: "luxury",
        categoryId: "cars",
        count: 23,
      },
      {
        id: "motorcycles",
        name: "دراجات نارية",
        slug: "motorcycles",
        categoryId: "cars",
        count: 34,
      },
    ],
  },
  {
    id: "electronics",
    name: "إلكترونيات",
    slug: "electronics",
    image: "/assets/images/categories/electronics.jpg",
    icon: "�",
    description: "أحدث الأجهزة الإلكترونية والتكنولوجيا",
    subcategories: [
      {
        id: "phones",
        name: "هواتف ذكية",
        slug: "phones",
        categoryId: "electronics",
        count: 234,
      },
      {
        id: "laptops",
        name: "لابتوب",
        slug: "laptops",
        categoryId: "electronics",
        count: 123,
      },
      {
        id: "tablets",
        name: "تابلت",
        slug: "tablets",
        categoryId: "electronics",
        count: 67,
      },
      {
        id: "cameras",
        name: "كاميرات",
        slug: "cameras",
        categoryId: "electronics",
        count: 45,
      },
      {
        id: "gaming",
        name: "ألعاب إلكترونية",
        slug: "gaming",
        categoryId: "electronics",
        count: 89,
      },
      {
        id: "accessories",
        name: "اكسسوارات",
        slug: "accessories",
        categoryId: "electronics",
        count: 156,
      },
    ],
  },
  {
    id: "real-estate",
    name: "عقارات",
    slug: "real-estate",
    image: "/assets/images/categories/real-estate.jpg",
    icon: "🏠",
    description: "عقارات للبيع والإيجار",
    subcategories: [
      {
        id: "apartments",
        name: "شقق للإيجار",
        slug: "apartments",
        categoryId: "real-estate",
        count: 345,
      },
      {
        id: "houses-rent",
        name: "فلل للإيجار",
        slug: "houses-rent",
        categoryId: "real-estate",
        count: 123,
      },
      {
        id: "apartments-sale",
        name: "شقق للبيع",
        slug: "apartments-sale",
        categoryId: "real-estate",
        count: 234,
      },
      {
        id: "houses-sale",
        name: "فلل للبيع",
        slug: "houses-sale",
        categoryId: "real-estate",
        count: 167,
      },
      {
        id: "commercial",
        name: "عقارات تجارية",
        slug: "commercial",
        categoryId: "real-estate",
        count: 78,
      },
      {
        id: "land",
        name: "أراضي",
        slug: "land",
        categoryId: "real-estate",
        count: 89,
      },
    ],
  },
  {
    id: "furniture",
    name: "أثاث",
    slug: "furniture",
    image: "/assets/images/categories/furniture.jpg",
    icon: "🛋️",
    description: "أثاث منزلي ومكتبي",
    subcategories: [
      {
        id: "bedroom",
        name: "غرف نوم",
        slug: "bedroom",
        categoryId: "furniture",
        count: 123,
      },
      {
        id: "living-room",
        name: "صالات",
        slug: "living-room",
        categoryId: "furniture",
        count: 89,
      },
      {
        id: "dining",
        name: "غرف طعام",
        slug: "dining",
        categoryId: "furniture",
        count: 67,
      },
      {
        id: "office",
        name: "مكاتب",
        slug: "office",
        categoryId: "furniture",
        count: 45,
      },
      {
        id: "kitchen",
        name: "مطابخ",
        slug: "kitchen",
        categoryId: "furniture",
        count: 78,
      },
      {
        id: "outdoor",
        name: "أثاث خارجي",
        slug: "outdoor",
        categoryId: "furniture",
        count: 34,
      },
    ],
  },
  {
    id: "sports",
    name: "رياضة",
    slug: "sports",
    image: "/assets/images/categories/sports.jpg",
    icon: "⚽",
    description: "معدات ولوازم رياضية",
    subcategories: [
      {
        id: "fitness",
        name: "لياقة بدنية",
        slug: "fitness",
        categoryId: "sports",
        count: 67,
      },
      {
        id: "bikes",
        name: "دراجات هوائية",
        slug: "bikes",
        categoryId: "sports",
        count: 45,
      },
      {
        id: "football",
        name: "كرة قدم",
        slug: "football",
        categoryId: "sports",
        count: 89,
      },
      {
        id: "swimming",
        name: "سباحة",
        slug: "swimming",
        categoryId: "sports",
        count: 34,
      },
      {
        id: "gym",
        name: "معدات جيم",
        slug: "gym",
        categoryId: "sports",
        count: 56,
      },
      {
        id: "outdoor-sports",
        name: "رياضات خارجية",
        slug: "outdoor-sports",
        categoryId: "sports",
        count: 23,
      },
    ],
  },
  {
    id: "fashion",
    name: "أزياء",
    slug: "fashion",
    image: "/assets/images/categories/fashion.jpg",
    icon: "👗",
    description: "ملابس وإكسسوارات",
    subcategories: [
      {
        id: "men-clothing",
        name: "ملابس رجالية",
        slug: "men-clothing",
        categoryId: "fashion",
        count: 145,
      },
      {
        id: "women-clothing",
        name: "ملابس نسائية",
        slug: "women-clothing",
        categoryId: "fashion",
        count: 234,
      },
      {
        id: "shoes",
        name: "أحذية",
        slug: "shoes",
        categoryId: "fashion",
        count: 123,
      },
      {
        id: "bags",
        name: "حقائب",
        slug: "bags",
        categoryId: "fashion",
        count: 78,
      },
      {
        id: "accessories",
        name: "اكسسوارات",
        slug: "accessories",
        categoryId: "fashion",
        count: 89,
      },
      {
        id: "watches",
        name: "ساعات",
        slug: "watches",
        categoryId: "fashion",
        count: 56,
      },
    ],
  },
];

export const mockAds: Ad[] = [
  {
    id: 1,
    title: "آيفون 15 برو ماكس - حالة ممتازة",
    description:
      "آيفون 15 برو ماكس بحالة ممتازة. مستخدم لفترة قصيرة، يأتي مع الصندوق الأصلي والشاحن.",
    price: 1200,
    currency: "USD",
    location: "الرياض، السعودية",
    category: "electronics",
    subcategory: "phones",
    image:
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1200&q=80",
    ],
    postedDate: "منذ 3 أيام",
    seller: "أحمد علي",
    sellerId: "user1",
    featured: false,
    condition: "used",
    views: 342,
    isNegotiable: true,
    phone: "+966-55-123-4567",
  },
  {
    id: 2,
    title: "BMW X5 2022 - فل كامل",
    description:
      "BMW X5 موديل 2022، فل كامل، بحالة ممتازة. عداد قليل، تحت الضمان. صيانة دورية منتظمة.",
    price: 85000,
    currency: "USD",
    location: "دبي، الإمارات",
    category: "cars",
    subcategory: "suv",
    image:
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=1200&q=80",
    ],
    postedDate: "منذ يوم واحد",
    seller: "معرض الفخامة للسيارات",
    sellerId: "user2",
    featured: true,
    condition: "used",
    views: 1289,
    isNegotiable: true,
    phone: "+971-50-987-6543",
  },
  {
    id: 3,
    title: "طقم غرفة نوم مودرن - جديد",
    description:
      "طقم غرفة نوم مودرن وأنيق، جديد تماماً ولم يُستخدم. يشمل السرير والدولاب والكومودينو.",
    price: 1200,
    currency: "USD",
    location: "جدة، السعودية",
    category: "furniture",
    subcategory: "bedroom",
    image:
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=1200&q=80",
    ],
    postedDate: "منذ 5 أيام",
    seller: "معرض الأثاث الراقي",
    sellerId: "user3",
    featured: false,
    condition: "new",
    views: 214,
    isNegotiable: true,
    phone: "+966-50-222-3333",
  },
  {
    id: 4,
    title: "كاميرا كانون EOS R5 - احترافية",
    description:
      "كاميرا احترافية كانون EOS R5 بحالة ممتازة. مناسبة لهواة ومحترفي التصوير. معها عدسة 24-70mm.",
    price: 2500,
    currency: "USD",
    location: "الكويت، الكويت",
    category: "electronics",
    subcategory: "cameras",
    image:
      "https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1606983340126-99ab4feaa64a?auto=format&fit=crop&w=1200&q=80",
    ],
    postedDate: "منذ أسبوع",
    seller: "محترف التصوير",
    sellerId: "user4",
    featured: false,
    condition: "used",
    views: 487,
    isNegotiable: true,
    phone: "+965-55-444-5555",
  },
  {
    id: 5,
    title: "شقة للإيجار 3 غرف - حي راقي",
    description:
      "شقة فاخرة للإيجار، 3 غرف نوم، 2 حمام، صالة واسعة، مطبخ مجهز. في حي راقي وهادئ.",
    price: 1500,
    currency: "USD",
    location: "عمان، الأردن",
    category: "real-estate",
    subcategory: "apartments",
    image:
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
    ],
    postedDate: "منذ يومين",
    seller: "مكتب العقارات المميزة",
    sellerId: "user5",
    featured: true,
    condition: "new",
    views: 856,
    isNegotiable: false,
    phone: "+962-79-666-7777",
  },
  {
    id: 6,
    title: "جهاز جيم متكامل - حالة جيدة",
    description:
      "جهاز جيم متكامل لجميع عضلات الجسم. حالة جيدة جداً، نظيف ومعتنى به. مناسب للاستخدام المنزلي.",
    price: 800,
    currency: "USD",
    location: "الدوحة، قطر",
    category: "sports",
    subcategory: "gym",
    image:
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1200&q=80",
    ],
    postedDate: "منذ 4 أيام",
    seller: "محب الرياضة",
    sellerId: "user6",
    featured: false,
    condition: "used",
    views: 156,
    isNegotiable: true,
    phone: "+974-55-888-9999",
  },
  {
    id: 7,
    title: "فستان سهرة أنيق - جديد",
    description:
      "فستان سهرة أنيق ومميز، جديد تماماً مع العلامات. مقاس M. مناسب للمناسبات الخاصة.",
    price: 250,
    currency: "USD",
    location: "بيروت، لبنان",
    category: "fashion",
    subcategory: "women-clothing",
    image:
      "https://images.unsplash.com/photo-1566479179817-9eea936d69e1?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1566479179817-9eea936d69e1?auto=format&fit=crop&w=1200&q=80",
    ],
    postedDate: "منذ 6 أيام",
    seller: "متجر الأناقة",
    sellerId: "user7",
    featured: false,
    condition: "new",
    views: 293,
    isNegotiable: false,
    phone: "+961-70-111-2222",
  },
  {
    id: 8,
    title: "لابتوب ديل XPS 13 - خفيف ومحمول",
    description:
      "لابتوب ديل XPS 13، معالج Intel i7، ذاكرة 16GB، تخزين SSD 512GB. خفيف ومثالي للعمل والدراسة.",
    price: 1100,
    currency: "USD",
    location: "الدار البيضاء، المغرب",
    category: "electronics",
    subcategory: "laptops",
    image:
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=80",
    ],
    postedDate: "منذ 3 أيام",
    seller: "طالب جامعي",
    sellerId: "user8",
    featured: false,
    condition: "used",
    views: 578,
    isNegotiable: true,
    phone: "+212-6-333-4444",
  },
  {
    id: 9,
    title: "دراجة هوائية جبلية - ممتازة",
    description:
      "دراجة هوائية جبلية احترافية، 21 سرعة، إطارات قوية. مناسبة لجميع التضاريس، صيانة حديثة.",
    price: 350,
    currency: "USD",
    location: "تونس، تونس",
    category: "sports",
    subcategory: "bikes",
    image:
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1200&q=80",
    ],
    postedDate: "منذ أسبوع",
    seller: "محب الدراجات",
    sellerId: "user9",
    featured: false,
    condition: "used",
    views: 127,
    isNegotiable: true,
    phone: "+216-22-555-6666",
  },
  {
    id: 10,
    title: "طاولة طعام خشبية - كلاسيكية",
    description:
      "طاولة طعام خشبية كلاسيكية أنيقة، تتسع لـ 6 أشخاص. خشب طبيعي عالي الجودة، تصميم تقليدي جميل.",
    price: 600,
    currency: "USD",
    location: "أبوظبي، الإمارات",
    category: "furniture",
    subcategory: "dining",
    image:
      "https://images.unsplash.com/photo-1549497538-303791108f95?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1549497538-303791108f95?auto=format&fit=crop&w=1200&q=80",
    ],
    postedDate: "منذ 5 أيام",
    seller: "محل الأثاث التراثي",
    sellerId: "user10",
    featured: true,
    condition: "used",
    views: 445,
    isNegotiable: true,
    phone: "+971-50-777-8888",
  },
  {
    id: 11,
    title: "تويوتا كامري 2021 - موثوقة",
    description:
      "تويوتا كامري 2021، حالة ممتازة، عداد قليل. سيارة موثوقة واقتصادية في استهلاك الوقود.",
    price: 28000,
    currency: "USD",
    location: "مسقط، عمان",
    category: "cars",
    subcategory: "sedan",
    image:
      "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=1200&q=80",
    ],
    postedDate: "منذ يومين",
    seller: "معرض السيارات الموثوقة",
    sellerId: "user11",
    featured: false,
    condition: "used",
    views: 723,
    isNegotiable: true,
    phone: "+968-99-999-0000",
  },
  {
    id: 12,
    title: "ساعة رولكس أصلية - فاخرة",
    description:
      "ساعة رولكس أصلية، موديل كلاسيكي، حالة ممتازة. معها الضمان والصندوق الأصلي. استثمار رائع.",
    price: 8500,
    currency: "USD",
    location: "الكويت، الكويت",
    category: "fashion",
    subcategory: "watches",
    image:
      "https://images.unsplash.com/photo-1523170335258-f5c6c6bd6eeb?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1523170335258-f5c6c6bd6eeb?auto=format&fit=crop&w=1200&q=80",
    ],
    postedDate: "منذ 3 أيام",
    seller: "هاوي الساعات الفاخرة",
    sellerId: "user12",
    featured: true,
    condition: "used",
    views: 1245,
    isNegotiable: false,
    phone: "+965-55-123-9876",
  },
];
