name: Deploy to Production

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: "20"

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Type check
        run: npx tsc --noEmit

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: lint-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
        env:
          NEXTAUTH_SECRET: "Kmo08F5rO40134hP0OFo8BZmqdzIliiSLiJdw/SlzyU="
          NEXTAUTH_URL: "https://ealaany.com"
          NODE_ENV: production

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: |
            .next/
            public/
            package.json
            package-lock.json

  deploy-vps:
    name: Deploy to VPS Server
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-files

      - name: Deploy to VPS Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: "92.112.192.245"
          username: "kareem"
          key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
            QyNTUxOQAAACB18E4FcMcWaD2V9JR/fYGW4dm90rl1cBkSe6JDcUtF0wAAAKhXVZlBV1WZ
            QQAAAAtzc2gtZWQyNTUxOQAAACB18E4FcMcWaD2V9JR/fYGW4dm90rl1cBkSe6JDcUtF0w
            AAAECxEmBMlPHWpkm//Gx9cIA/GdxpIspm3P8bHp2kueaWBHXwTgVwxxZoPZX0lH99gZbh
            2b3SuXVwGRJ7okNxS0XTAAAAH2thcmVlbUBNYWNCb29rLUFpci1LYXJlZW0ubG9jYWwBAg
            MEBQY=
            -----END OPENSSH PRIVATE KEY-----
          port: 22
          script: |
            # Check if repository exists, if not clone it
            if [ ! -d "/home/kareem/elaany-app" ]; then
              echo "🔄 Repository not found, cloning..."
              cd /home/kareem
              git clone https://github.com/kareem-shimes/elaany-app.git
              cd elaany-app
            else
              echo "🔄 Repository exists, pulling latest changes..."
              cd /home/kareem/elaany-app
              # Reset any local changes
              git reset --hard
              git clean -fd
              git pull origin main
            fi

            # Install dependencies and build
            npm ci
            export NEXTAUTH_SECRET="Kmo08F5rO40134hP0OFo8BZmqdzIliiSLiJdw/SlzyU="
            export NEXTAUTH_URL="https://ealaany.com"
            npm run build

            # Restart or start the application with PM2
            pm2 restart nextjs-app || pm2 start npm --name "nextjs-app" -- start
            pm2 save
            echo "✅ Deployment completed successfully!"
